# A faily standard FedAvg strategy for FLower

_target_: flwr.server.strategy.FedAvg # we point to a class (in the code we will use `hydra.utils.instantiate(<this_node>)` to create the object)
fraction_fit: 0.0001 # by setting this to a very low number, we can easily control how many clients participate in simulation with a single scalar (i.e. server.clients_per_round) -- see logic here for details: https://github.com/adap/flower/blob/1b4b659204c406bb4fd7821d39a689105543ecbe/src/py/flwr/server/strategy/fedavg.py#L143
fraction_evaluate: 0.0 # no clients will be sampled for federated evaluation (we will still perform global evaluation)
min_fit_clients: ${server.clients_per_round}
min_available_clients: ${server.pool}
on_fit_config_fn:
  _target_: src.server.gen_fit_config # function to call eventually
  fit_cfg: ${server.fit_cfg}