---
!include configs/base.yaml
---

# here we extend the base config so the model is a ResNet18 adapted for CIFAR-10
# Because this is a much larger model, we also raise the resources Ray grants to each client

model:
  build: !bind:src.models.ResNet18
    num_classes: 10

client:
  resources:
    num_cpus: 4
    num_gpus: 0.5